# Generated by Django 4.2.5 on 2023-09-16 20:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_alter_entry_content_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
