# Generated by Django 4.2.5 on 2023-09-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0004_alter_entry_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='puclic',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
