# Generated by Django 4.2.5 on 2023-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0006_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='Entry', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='puclic',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
