# Generated by Django 4.2.5 on 2023-09-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0009_alter_entry_puclic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='puclic',
            field=models.BooleanField(default=False),
        ),
    ]
