# Generated by Django 4.2.5 on 2023-09-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0010_alter_entry_puclic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(null=True, upload_to='Entry', verbose_name='Imagen'),
        ),
    ]
