# Generated by Django 4.2.5 on 2023-09-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0011_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(default=1, upload_to='Entry', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
